services:
    jena-fuseki:
        image: ${IMAGE_VERSION}
        restart: "no"
        profiles: ["test.jena-fuseki"]
        ports:
        -   "${PORT}:3030"
        container_name: ${CONTAINER_NAME}
        volumes:
        -   ${STORE_FOLDER}:/fuseki
        environment:
        -   ADMIN_PASSWORD=${ADMIN_PASSWORD}
